event_list=[
    {"event": "LOAD", "time": 0, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "FACTORY", "cargo": [{"cargo_id": 0, "destination": "A", "origin": "FACTORY"}]},
    {"event": "LOAD", "time": 0, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "cargo": [{"cargo_id": 1, "destination": "A", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 0, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "FACTORY", "destination": "PORT", "cargo": [{"cargo_id": 0, "destination": "A", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 0, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "destination": "PORT", "cargo": [{"cargo_id": 1, "destination": "A", "origin": "FACTORY"}]},
    {"event": "ARRIVE", "time": 1, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "PORT", "cargo": [{"cargo_id": 0, "destination": "A", "origin": "FACTORY"}]},
    {"event": "ARRIVE", "time": 1, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "PORT", "cargo": [{"cargo_id": 1, "destination": "A", "origin": "FACTORY"}]},
    {"event": "UNLOAD", "time": 1, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "PORT", "cargo": [{"cargo_id": 0, "destination": "A", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 1, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "PORT", "destination": "FACTORY", "cargo": []},
    {"event": "UNLOAD", "time": 1, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "PORT", "cargo": [{"cargo_id": 1, "destination": "A", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 1, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "PORT", "destination": "FACTORY", "cargo": []},
    {"event": "LOAD", "time": 2, "transport_id": "FERRY", "kind": "FERRY", "location": "PORT", "cargo": [{"cargo_id": 0, "destination": "A", "origin": "FACTORY"}, {"cargo_id": 1, "destination": "A", "origin": "FACTORY"}]},
    {"event": "ARRIVE", "time": 2, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "FACTORY", "cargo": []},
    {"event": "LOAD", "time": 2, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "FACTORY", "cargo": [{"cargo_id": 2, "destination": "B", "origin": "FACTORY"}]},
    {"event": "ARRIVE", "time": 2, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "cargo": []},
    {"event": "LOAD", "time": 2, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "cargo": [{"cargo_id": 3, "destination": "A", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 2, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "FACTORY", "destination": "B", "cargo": [{"cargo_id": 2, "destination": "B", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 2, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "destination": "PORT", "cargo": [{"cargo_id": 3, "destination": "A", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 3, "transport_id": "FERRY", "kind": "FERRY", "location": "PORT", "destination": "A", "cargo": [{"cargo_id": 0, "destination": "A", "origin": "FACTORY"}, {"cargo_id": 1, "destination": "A", "origin": "FACTORY"}]},
    {"event": "ARRIVE", "time": 3, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "PORT", "cargo": [{"cargo_id": 3, "destination": "A", "origin": "FACTORY"}]},
    {"event": "UNLOAD", "time": 3, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "PORT", "cargo": [{"cargo_id": 3, "destination": "A", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 3, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "PORT", "destination": "FACTORY", "cargo": []},
    {"event": "ARRIVE", "time": 4, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "cargo": []},
    {"event": "LOAD", "time": 4, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "cargo": [{"cargo_id": 4, "destination": "B", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 4, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "destination": "B", "cargo": [{"cargo_id": 4, "destination": "B", "origin": "FACTORY"}]},
    {"event": "ARRIVE", "time": 7, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "B", "cargo": [{"cargo_id": 2, "destination": "B", "origin": "FACTORY"}]},
    {"event": "UNLOAD", "time": 7, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "B", "cargo": [{"cargo_id": 2, "destination": "B", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 7, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "B", "destination": "FACTORY", "cargo": []},
    {"event": "ARRIVE", "time": 9, "transport_id": "FERRY", "kind": "FERRY", "location": "A", "cargo": [{"cargo_id": 0, "destination": "A", "origin": "FACTORY"}, {"cargo_id": 1, "destination": "A", "origin": "FACTORY"}]},
    {"event": "ARRIVE", "time": 9, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "B", "cargo": [{"cargo_id": 4, "destination": "B", "origin": "FACTORY"}]},
    {"event": "UNLOAD", "time": 9, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "B", "cargo": [{"cargo_id": 4, "destination": "B", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 9, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "B", "destination": "FACTORY", "cargo": []},
    {"event": "UNLOAD", "time": 10, "transport_id": "FERRY", "kind": "FERRY", "location": "A", "cargo": [{"cargo_id": 0, "destination": "A", "origin": "FACTORY"}, {"cargo_id": 1, "destination": "A", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 10, "transport_id": "FERRY", "kind": "FERRY", "location": "A", "destination": "PORT", "cargo": []},
    {"event": "ARRIVE", "time": 12, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "FACTORY", "cargo": []},
    {"event": "LOAD", "time": 12, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "FACTORY", "cargo": [{"cargo_id": 5, "destination": "B", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 12, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "FACTORY", "destination": "B", "cargo": [{"cargo_id": 5, "destination": "B", "origin": "FACTORY"}]},
    {"event": "ARRIVE", "time": 14, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "cargo": []},
    {"event": "LOAD", "time": 14, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "cargo": [{"cargo_id": 6, "destination": "A", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 14, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "destination": "PORT", "cargo": [{"cargo_id": 6, "destination": "A", "origin": "FACTORY"}]},
    {"event": "ARRIVE", "time": 15, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "PORT", "cargo": [{"cargo_id": 6, "destination": "A", "origin": "FACTORY"}]},
    {"event": "UNLOAD", "time": 15, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "PORT", "cargo": [{"cargo_id": 6, "destination": "A", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 15, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "PORT", "destination": "FACTORY", "cargo": []},
    {"event": "ARRIVE", "time": 16, "transport_id": "FERRY", "kind": "FERRY", "location": "PORT", "cargo": []},
    {"event": "LOAD", "time": 16, "transport_id": "FERRY", "kind": "FERRY", "location": "PORT", "cargo": [{"cargo_id": 3, "destination": "A", "origin": "FACTORY"}, {"cargo_id": 6, "destination": "A", "origin": "FACTORY"}]},
    {"event": "ARRIVE", "time": 16, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "cargo": []},
    {"event": "LOAD", "time": 16, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "cargo": [{"cargo_id": 7, "destination": "B", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 16, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "FACTORY", "destination": "B", "cargo": [{"cargo_id": 7, "destination": "B", "origin": "FACTORY"}]},
    {"event": "ARRIVE", "time": 17, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "B", "cargo": [{"cargo_id": 5, "destination": "B", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 17, "transport_id": "FERRY", "kind": "FERRY", "location": "PORT", "destination": "A", "cargo": [{"cargo_id": 3, "destination": "A", "origin": "FACTORY"}, {"cargo_id": 6, "destination": "A", "origin": "FACTORY"}]},
    {"event": "UNLOAD", "time": 17, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "B", "cargo": [{"cargo_id": 5, "destination": "B", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 17, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "B", "destination": "FACTORY", "cargo": []},
    {"event": "ARRIVE", "time": 21, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "B", "cargo": [{"cargo_id": 7, "destination": "B", "origin": "FACTORY"}]},
    {"event": "UNLOAD", "time": 21, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "B", "cargo": [{"cargo_id": 7, "destination": "B", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 21, "transport_id": "TRUCK2", "kind": "TRUCK", "location": "B", "destination": "FACTORY", "cargo": []},
    {"event": "ARRIVE", "time": 22, "transport_id": "TRUCK1", "kind": "TRUCK", "location": "FACTORY", "cargo": []},
    {"event": "ARRIVE", "time": 23, "transport_id": "FERRY", "kind": "FERRY", "location": "A", "cargo": [{"cargo_id": 3, "destination": "A", "origin": "FACTORY"}, {"cargo_id": 6, "destination": "A", "origin": "FACTORY"}]},
    {"event": "UNLOAD", "time": 24, "transport_id": "FERRY", "kind": "FERRY", "location": "A", "cargo": [{"cargo_id": 3, "destination": "A", "origin": "FACTORY"}, {"cargo_id": 6, "destination": "A", "origin": "FACTORY"}]},
    {"event": "DEPART", "time": 24, "transport_id": "FERRY", "kind": "FERRY", "location": "A", "destination": "PORT", "cargo": []}
]